// src/types/products.ts

export type Category = "Fresh Fish" | "Shellfish" | "Dry Seafood";

export interface Product {
  id: number;
  name: string;
  category: Category;
  price: number;
  unit: string;
  netWeight: string;
  grossWeight?: string;
  image: string;
  featured?: boolean;
}

export const products: Product[] = [
  // 🦞 SHELLFISH
  {
    id: 1,
    name: "Lobster Large Size",
    category: "Shellfish",
    price: 1999,
    unit: "kg",
    netWeight: "800 grams",
    grossWeight: "1 kg",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984688/lobster_fldpfh.jpg",
    featured: true,
  },
  {
    id: 2,
    name: "Lobster Medium Size",
    category: "Shellfish",
    price: 1000,
    unit: "kg",
    netWeight: "800 grams",
    grossWeight: "1 kg count 4 to 5 pieces",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984688/lobster_fldpfh.jpg",
    featured: true,
  },
  {
    id: 3,
    name: "White Prawns",
    category: "Shellfish",
    price: 600,
    unit: "kg",
    netWeight: "500 grams",
    grossWeight: "1 kg count 20 to 30 pieces",
    image: "https://sethlui.com/wp-content/uploads/2021/06/raw-white-prawn.jpg",
    featured: true,
  },
  {
    id: 4,
    name: "Tiger Prawns Large Size",
    category: "Shellfish",
    price: 1400,
    unit: "kg",
    netWeight: "500 grams",
    grossWeight: "1 kg count 10 to 12 pieces",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984688/sea-tiger-prawns_utlkgr.jpg",
    featured: true,
  },
  {
    id: 5,
    name: "Tiger Prawns Medium Size",
    category: "Shellfish",
    price: 1250,
    unit: "kg",
    netWeight: "500 grams",
    grossWeight: "1 kg count 10 to 15 pieces",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984688/sea-tiger-prawns_utlkgr.jpg",
  },
  {
    id: 6,
    name: "Brown Prawns",
    category: "Shellfish",
    price: 500,
    unit: "kg",
    netWeight: "500 grams",
    grossWeight: "1 kg count 40 to 50 pieces",
    image: "https://i.pinimg.com/1200x/44/93/3d/44933d1f85d4704b529062648358ac18.jpg",
  },
  {
    id: 7,
    name: "Blue Crabs (Large)",
    category: "Shellfish",
    price: 600,
    unit: "kg",
    netWeight: "500 grams",
    grossWeight: "1 kg count 4 to 6 pieces",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1766123612/blue-crab_kjaac5.jpg",
  },
  {
    id: 8,
    name: "Live Crabs",
    category: "Shellfish",
    price: 600,
    unit: "kg",
    netWeight: "700 grams",
    grossWeight: "1 kg count 3 to 5 pieces",
    image: "https://i.pinimg.com/736x/88/27/d0/8827d0eb5d554a7ec75b58656c1769a7.jpg",
  },
  {
    id: 9,
    name: "3 Dot Crabs",
    category: "Shellfish",
    price: 300,
    unit: "kg",
    netWeight: "500 grams",
    grossWeight: "1 kg count 6 to 8 pieces",
    image: "https://i.pinimg.com/1200x/19/40/bb/1940bb1440caca03b587051bc2ec118a.jpg",
  },
  {
    id: 10,
    name: "Squid Fish",
    category: "Shellfish",
    price: 500,
    unit: "kg",
    netWeight: "500 grams",
    grossWeight: "1 kg",
    image: "https://i.pinimg.com/736x/c1/93/45/c193458dd8791449827331531e268771.jpg",
  },
  {
    id: 11,
    name: "Octopus",
    category: "Shellfish",
    price: 600,
    unit: "kg",
    netWeight: "600–700 grams",
    grossWeight: "1 kg",
    image: "https://i.pinimg.com/1200x/88/5d/db/885ddb763a601149e2159bdcbfef57a8.jpg",
  },

  // 🐟 FRESH FISH
  {
    id: 12,
    name: "King Fish Curry Cut",
    category: "Fresh Fish",
    price: 800,
    unit: "kg",
    netWeight: "800 grams",
    grossWeight: "1 kg",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984687/king-fish-curry-cut_pjer5e.jpg",
    featured: true,
  },
  {
    id: 13,
    name: "King Fish – Konam",
    category: "Fresh Fish",
    price: 900,
    unit: "kg",
    netWeight: "800 grams",
    grossWeight: "1 kg count 10 to 15 pieces",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984687/king-fish_w4kemm.jpg",
    featured: true,
  },
  {
    id: 14,
    name: "King Fish Fillet (Konam)",
    category: "Fresh Fish",
    price: 1300,
    unit: "1.5 kg",
    netWeight: "600 grams",
    grossWeight: "1.5 kg",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984687/king-fish-boneless-fillet-cubes_w8hsac.jpg",
  },
  {
    id: 15,
    name: "King Fish Heads - Konam",
    category: "Fresh Fish",
    price: 300,
    unit: "kg",
    netWeight: "600 grams",
    grossWeight: "1 kg",
    image: "https://www.norsupplies.com/wp-content/uploads/2023/04/King-Fish-Heads-for-soup.png",
  },
  {
    id: 16,
    name: "Chinese Pomfret (Large)",
    category: "Fresh Fish",
    price: 1600,
    unit: "kg",
    netWeight: "800 grams",
    grossWeight: "1 kg count 2 pieces",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984686/chinese-pomfret_lum3ht.jpg",
    featured: true,
  },
  {
    id: 17,
    name: "Chinese Pomfret (Medium)",
    category: "Fresh Fish",
    price: 1400,
    unit: "kg",
    netWeight: "800 grams",
    grossWeight: "1 kg count 2 to 3 pieces",
    image: "https://i.pinimg.com/1200x/fa/4a/1e/fa4a1ec804d1d653c69fc70c3934b926.jpg",
  },
  {
    id: 18,
    name: "White Pomfret (Large)",
    category: "Fresh Fish",
    price: 1450,
    unit: "kg",
    netWeight: "800 grams",
    grossWeight: "1 kg count 2-3 pieces whole cleaned",
    image: "https://m.media-amazon.com/images/I/41xOpahw9XL.jpg",
  },
  {
    id: 19,
    name: "White Pomfret (Medium)",
    category: "Fresh Fish",
    price: 1350,
    unit: "kg",
    netWeight: "800 grams",
    grossWeight: "1 kg count 4 to 5 pieces whole cleaned",
    image: "http://www.bombayfisheries.com/cdn/shop/files/white-pomfret-whole-cleaned.png?v=1687610102",
  },
  {
    id: 20,
    name: "Black Pomfret",
    category: "Fresh Fish",
    price: 600,
    unit: "kg",
    netWeight: "800 grams",
    grossWeight: "1 kg count 3 to 5 pieces",
    image: "https://d1z88p83zuviay.cloudfront.net/ProductVariantImages/66297c99-35c1-4b53-9d69-b226e6a3af4b.jpg",
  },
  {
    id: 21,
    name: "Tuna Fish Curry Cut",
    category: "Fresh Fish",
    price: 400,
    unit: "kg",
    netWeight: "600 grams",
    grossWeight: "1 kg",
    image: "https://i.pinimg.com/736x/9c/3a/5f/9c3a5fea37f50ac24d0c353136661017.jpg",
  },
  {
    id: 22,
    name: "Anchovy Fish (Netthalu)",
    category: "Fresh Fish",
    price: 400,
    unit: "kg",
    netWeight: "600 grams",
    grossWeight: "1 kg",
    image: "https://i.pinimg.com/736x/59/ca/bb/59cabb1ec801d1829dc9aab3c75f9155.jpg",
  },
  {
    id: 23,
    name: "Mackerel Fish (Kanagadhala)",
    category: "Fresh Fish",
    price: 400,
    unit: "kg",
    netWeight: "700 grams",
    grossWeight: "1 kg",
    image: "https://www.healthifyme.com/blog/wp-content/uploads/2023/06/shutterstock_1829757968-1.jpg",
  },
  {
    id: 24,
    name: "Pink Perch (Gulivendalu)",
    category: "Fresh Fish",
    price: 400,
    unit: "kg",
    netWeight: "800 grams",
    grossWeight: "1 kg count 6 to 8 pieces",
    image: "http://doofdoof.in/cdn/shop/products/images_12.jpg?v=1668691097",
  },
  {
    id: 25,
    name: "Roopchand (Rive Fish)",
    category: "Fresh Fish",
    price: 270,
    unit: "kg",
    netWeight: "600 grams",
    grossWeight: "1 kg",
    image: "https://www.bayhawk.in/wp-content/uploads/2022/06/1.-Whole-Uncleaned-1280x840-13.jpg",
  },
  {
    id: 26,
    name: "Sheelavathi (River Fish)",
    category: "Fresh Fish",
    price: 270,
    unit: "kg",
    netWeight: "600 grams",
    grossWeight: "1 kg",
    image: "https://5.imimg.com/data5/KG/YT/TQ/ANDROID-15561967/product-jpeg-500x500.jpg",
  },
  {
    id: 27,
    name: "Milk Shark Fish",
    category: "Fresh Fish",
    price: 600,
    unit: "kg",
    netWeight: "500 grams",
    grossWeight: "1 kg",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984687/milkshake_hbci6s.jpg",
  },
  {
    id: 28,
    name: "Lady Fingers Fish",
    category: "Fresh Fish",
    price: 600,
    unit: "kg",
    netWeight: "600 grams",
    grossWeight: "1 kg",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984688/lady-fish_jytpjd.jpg",
  },

  // 🐟 DRY SEAFOOD
  {
    id: 29,
    name: "Dry Savadalu",
    category: "Dry Seafood",
    price: 200,
    unit: "250 g",
    netWeight: "250 grams",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765985868/savadalu_ei5vfg.jpg",
  },
  {
    id: 30,
    name: "Dry King Fish (Konam)",
    category: "Dry Seafood",
    price: 300,
    unit: "250 g",
    netWeight: "250 grams",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984687/dry-king-fish_uzkvra.jpg",
  },
  {
    id: 31,
    name: "Dry Squid",
    category: "Dry Seafood",
    price: 350,
    unit: "250 g",
    netWeight: "250 grams",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984687/dry-squid_fhd5em.jpg",
  },
  {
    id: 32,
    name: "Dry Anchovy (Medium)",
    category: "Dry Seafood",
    price: 200,
    unit: "250 g",
    netWeight: "250 grams",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984686/dry-anchovy_ap2jji.jpg",
  },
  {
    id: 33,
    name: "Dry Anchovy (Large)",
    category: "Dry Seafood",
    price: 250,
    unit: "250 g",
    netWeight: "250 grams",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984686/dry-anchovy_ap2jji.jpg",
  },
  {
    id: 34,
    name: "Dry Royyapottu (Prawns)",
    category: "Dry Seafood",
    price: 200,
    unit: "250 g",
    netWeight: "250 grams",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984687/dry-royopattu_azmzyz.jpg",
  },
  {
    id: 35,
    name: "Dry Prawns",
    category: "Dry Seafood",
    price: 250,
    unit: "250 g",
    netWeight: "250 grams",
    image: "https://res.cloudinary.com/de7icka3e/image/upload/v1765984686/dry-praws_jcec8c.jpg",
    featured: true,
  },
   {
    id: 36,
    name: "Seer Fish-Vanajaram",
    category: "Fresh Fish",
    price: 800,
    unit: "kg",
    netWeight: "800 grams",
    grossWeight: "1 kg count 10 to 15 pieces", 
    image: "https://5.imimg.com/data5/UI/JG/MY-37031394/vanjiram-fish-500x500.jpg",
  },
  {
  id: 37,
  name: "Pandugoppa Fish",
  category: "Fresh Fish",
  price: 750,
  unit: "kg",
  netWeight: "600 grams (after cleaning)",
  grossWeight: "Approx 1 kg before cleaning",
  image: "https://res.cloudinary.com/de7icka3e/image/upload/v1766123612/pandugoppa-fish_jxgtru.jpg",
  featured: false,
},
{
  id: 38,
  name: "Yellow Tuna Boneless Meat",
  category: "Fresh Fish",
  price: 550,
  unit: "600 g",
  netWeight: "600 grams (after cleaning)",
  grossWeight: "Boneless cut",
  image: "https://res.cloudinary.com/de7icka3e/image/upload/v1766123612/yellow-tuna-boneless-meat_ag8s2u.jpg",
  featured: false,
}

];
